services:
  web:
    image: "gutenbergsite:latest"
    build: "./docker"
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - type: "bind"
        source: "."
        target: "/gutenbergsite"
