name: Build Jekyll site

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      
      - name: Populate latest_covers
        run: |
          cp "./_includes/latest_covers_test.html" "./_includes/latest_covers.html"

      - name: Install Jekyll
        run: |
          gem install bundler
          bundle install
      
      - name: Build site
        run: bundle exec jekyll build -d build/
